### Pandas:

* Pandas is a one libtrary for reading, processing and analyze the data
* it is a one of the best library in datascience

* Pandas can be explore in two ways:
    * Series : It can be represent as 1-D data
    * DataFrame: It can be represent as 2-d data

### Data Frame:

In [1]:
# create a dataframe

import pandas as pd
import numpy as np

df=pd.DataFrame()
type(df)

pandas.core.frame.DataFrame

In [2]:
# Assign the data using list into DF
l=[10,20,15,25,36]
df=pd.DataFrame(l)
df

    0
0  10
1  20
2  15
3  25
4  36

In [3]:
l=[[10,20],[30,40],[50,60],[70,80]]
df=pd.DataFrame(l)
df

    0   1
0  10  20
1  30  40
2  50  60
3  70  80

In [4]:
l=[[10,20],[30,40],[50,60],[70,80]]
df=pd.DataFrame(l,columns=["first","second"])
df

   first  second
0     10      20
1     30      40
2     50      60
3     70      80

In [5]:
# pass the data using numpy into dataframe
a=np.array(['dharma teja','s kumar','pavan kumar','shankar'])
df=pd.DataFrame(a,columns=["Name"])
df

          Name
0  dharma teja
1      s kumar
2  pavan kumar
3      shankar

In [6]:
# pass the list of tuples into dataframe

l=[("A",30),("B",40),("c",50),("D",70)]
df=pd.DataFrame(l)
df.columns=["Name","value"]
df

  Name  value
0    A     30
1    B     40
2    c     50
3    D     70

In [7]:
# pass the data into df by using dictionary
d={"sno":[101,102,103,104],"sname":["A","B","C","D"]}
df=pd.DataFrame(d)
df

   sno sname
0  101     A
1  102     B
2  103     C
3  104     D

In [8]:
# update the column name
df.columns=["Student Number","Student Name"]
df

   Student Number Student Name
0             101            A
1             102            B
2             103            C
3             104            D

In [9]:
# How to add the new columns
df['Student Marks']=[50,60,70,25]
df

   Student Number Student Name  Student Marks
0             101            A             50
1             102            B             60
2             103            C             70
3             104            D             25

In [10]:
# How to add the new row 
new_row={"Student Number":105,"Student Name":"E","Student Marks":70}
df=df.append(new_row,ignore_index=True)
df

   Student Number Student Name  Student Marks
0             101            A             50
1             102            B             60
2             103            C             70
3             104            D             25
4             105            E             70

In [11]:
d={"sno":[101,102,103,104,105],'sname':["A","B","c","D","E"],'smarks':[50,60,70,80,30]}
df=pd.DataFrame(d,index=[1,2,3,4,5])
df

   sno sname  smarks
1  101     A      50
2  102     B      60
3  103     c      70
4  104     D      80
5  105     E      30

In [12]:
df.set_index('sno',inplace=True)

In [13]:
df

    sname  smarks
sno
101     A      50
102     B      60
103     c      70
104     D      80
105     E      30

In [14]:
df.reset_index(inplace=True)

In [15]:
df

   sno sname  smarks
0  101     A      50
1  102     B      60
2  103     c      70
3  104     D      80
4  105     E      30

### How to access the data from DataFrame

In [16]:
# access the columns name
df.columns

Index(['sno', 'sname', 'smarks'], dtype='object')

In [17]:
# access the index 
df.index

RangeIndex(start=0, stop=5, step=1)

In [18]:
d={"sno":[101,102,103,104,105],'sname':["A","B","c","D","E"],'smarks':[50,60,70,80,30]}
df=pd.DataFrame(d)
df

   sno sname  smarks
0  101     A      50
1  102     B      60
2  103     c      70
3  104     D      80
4  105     E      30

In [19]:
df['sno']

0    101
1    102
2    103
3    104
4    105
Name: sno, dtype: int64

In [20]:
type(df['sno'])

pandas.core.series.Series

In [21]:
df['sno'].ndim

1

In [22]:
df[['sno']]

   sno
0  101
1  102
2  103
3  104
4  105

In [23]:
type(df[['sno']])

pandas.core.frame.DataFrame

In [24]:
df[['sno']].ndim

2

In [25]:
df[['sno','sname']]

   sno sname
0  101     A
1  102     B
2  103     c
3  104     D
4  105     E

In [26]:
# access the data from row
df[:]

   sno sname  smarks
0  101     A      50
1  102     B      60
2  103     c      70
3  104     D      80
4  105     E      30

In [27]:
df[2:]

   sno sname  smarks
2  103     c      70
3  104     D      80
4  105     E      30

In [28]:
df[:3]

   sno sname  smarks
0  101     A      50
1  102     B      60
2  103     c      70

In [29]:
df[2:5]

   sno sname  smarks
2  103     c      70
3  104     D      80
4  105     E      30

In [30]:
# access the data using loc and iloc
#loc=>location
#iloc=>index location =>0,1,2,3....

In [31]:
df.loc[3]

sno       104
sname       D
smarks     80
Name: 3, dtype: object

In [32]:
df.loc[[3]]

   sno sname  smarks
3  104     D      80

In [33]:
df.loc[:3]

   sno sname  smarks
0  101     A      50
1  102     B      60
2  103     c      70
3  104     D      80

In [34]:
df.loc[3:]

   sno sname  smarks
3  104     D      80
4  105     E      30

In [35]:
df.loc[:1]

   sno sname  smarks
0  101     A      50
1  102     B      60

In [36]:
df.loc[:2,'sname':]

  sname  smarks
0     A      50
1     B      60
2     c      70

In [37]:
df.set_index('sname',inplace=True)

In [38]:
df

       sno  smarks
sname
A      101      50
B      102      60
c      103      70
D      104      80
E      105      30

In [39]:
df.loc['A']

sno       101
smarks     50
Name: A, dtype: int64

In [40]:
df.iloc[0]

sno       101
smarks     50
Name: A, dtype: int64

In [41]:
df.reset_index(inplace=True)

In [42]:
df

  sname  sno  smarks
0     A  101      50
1     B  102      60
2     c  103      70
3     D  104      80
4     E  105      30

In [43]:
df.iloc[1:4]

  sname  sno  smarks
1     B  102      60
2     c  103      70
3     D  104      80

In [44]:
df.iloc[1:4,:2]

  sname  sno
1     B  102
2     c  103
3     D  104

In [45]:
d={"sno":[101,102,103,104,105],'sname':["A","B","c","D","E"],'smarks':[50,60,70,80,30]}
df=pd.DataFrame(d)
df

   sno sname  smarks
0  101     A      50
1  102     B      60
2  103     c      70
3  104     D      80
4  105     E      30

In [46]:
df.iloc[3][1]

'D'

In [47]:
df.iloc[3,1]

'D'

In [48]:
df.loc[3,'sname']

'D'

In [49]:
d={'fname':["A","B","C","D","E"],
   "lname":["Android","Beta","Candy","Danger","Emo"],
   "smarks":[31,85,23,20,55]}
df=pd.DataFrame(d)
df

  fname    lname  smarks
0     A  Android      31
1     B     Beta      85
2     C    Candy      23
3     D   Danger      20
4     E      Emo      55

### 0-25 => fail
### 25-60 => second
### 60 above=>first

In [50]:
l=[]
for i in df['smarks']:
    if i>0 and i<=25:
        l.append("Fail")
    elif i>25 and i<60:
        l.append("Second")
    else:
        l.append("First")
df['student result']=l
df

  fname    lname  smarks student result
0     A  Android      31         Second
1     B     Beta      85          First
2     C    Candy      23           Fail
3     D   Danger      20           Fail
4     E      Emo      55         Second

In [51]:
df['student result']=='Fail'

0    False
1    False
2     True
3     True
4    False
Name: student result, dtype: bool

In [52]:
df[df['student result']=='Fail']

  fname   lname  smarks student result
2     C   Candy      23           Fail
3     D  Danger      20           Fail

In [53]:
df[df['smarks']>50]

  fname lname  smarks student result
1     B  Beta      85          First
4     E   Emo      55         Second

In [54]:
df[(df['smarks']<22)&(df['student result']=='Fail')]

  fname   lname  smarks student result
3     D  Danger      20           Fail

In [55]:
# Delete the columns
df=df.drop('student result',axis=1)
df

  fname    lname  smarks
0     A  Android      31
1     B     Beta      85
2     C    Candy      23
3     D   Danger      20
4     E      Emo      55

### manipulate files data into dataframe:

* CSV
    * pd.read_csv("filname.csv")
* Excel
    * pd.read_excel("filename.xlsx")
* JSON
    * pd.read_json("filename")
* HTML
    * pd.read_html("url")

In [56]:
#csv file access
df=pd.read_csv("weather.csv")  # d://folder1/filename.csv
df

    s.no        est  temparature  winspeed  humidity    event        city
0      1   1/2/2019           30        12     12.50     rain      guntur
1      1   1/2/2019           33        14     14.23     rain  vijayawada
2      2   1/3/2019           43        13     43.13     rain       vizag
3      3   1/4/2019           55         8     55.80  fullair      guntur
4      4   1/5/2019           66        10     66.10     cold  vijayawada
5      5   1/6/2019           34        15     34.15     cold       vizag
6      6   1/7/2019           76        17     76.17  fullair      guntur
7      7   1/8/2019           89        23     89.23     cold  vijayawada
8      8   1/9/2019           23         9     23.90  fullair       vizag
9      9  1/10/2019           90        11     90.11     cold      guntur
10    10  1/11/2019           65        18     65.18  fullair  vijayawada
11    11  1/12/2019           78        20     78.20  fullair       vizag

In [57]:
# how many rows and how many columns
df.shape

(12, 7)

In [58]:
df=df.drop('s.no',axis=1)
df

          est  temparature  winspeed  humidity    event        city
0    1/2/2019           30        12     12.50     rain      guntur
1    1/2/2019           33        14     14.23     rain  vijayawada
2    1/3/2019           43        13     43.13     rain       vizag
3    1/4/2019           55         8     55.80  fullair      guntur
4    1/5/2019           66        10     66.10     cold  vijayawada
5    1/6/2019           34        15     34.15     cold       vizag
6    1/7/2019           76        17     76.17  fullair      guntur
7    1/8/2019           89        23     89.23     cold  vijayawada
8    1/9/2019           23         9     23.90  fullair       vizag
9   1/10/2019           90        11     90.11     cold      guntur
10  1/11/2019           65        18     65.18  fullair  vijayawada
11  1/12/2019           78        20     78.20  fullair       vizag

In [59]:
df.head()

        est  temparature  winspeed  humidity    event        city
0  1/2/2019           30        12     12.50     rain      guntur
1  1/2/2019           33        14     14.23     rain  vijayawada
2  1/3/2019           43        13     43.13     rain       vizag
3  1/4/2019           55         8     55.80  fullair      guntur
4  1/5/2019           66        10     66.10     cold  vijayawada

In [60]:
df.head(2)

        est  temparature  winspeed  humidity event        city
0  1/2/2019           30        12     12.50  rain      guntur
1  1/2/2019           33        14     14.23  rain  vijayawada