In [9]:
import pandas as pd
df=pd.read_csv("UScomments.csv")
df

ParserError: Error tokenizing data. C error: Expected 4 fields in line 41589, saw 11

In [6]:
import pandas as pd

df = pd.read_csv(
    "UScomments.csv",
    on_bad_lines='skip',           # Skip rows with errors
    quoting=1,                     # Handle quoted fields properly (QUOTE_ALL)
    encoding='utf-8',              # Ensure proper character decoding
    low_memory=False               # Prevent dtype guessing errors
)

print(df.head())

      video_id                                       comment_text likes  \
0  XpVt6Z1Gjjo                  Logan Paul it's yo big day ‼️‼️‼️     4
1  XpVt6Z1Gjjo  I've been following you from the start of your...     3
2  XpVt6Z1Gjjo                 Say hi to Kong and maverick for me     3
3  XpVt6Z1Gjjo                                MY FAN . attendance     3
4  XpVt6Z1Gjjo                                         trending 😉     3

  replies
0       0
1       0
2       0
3       0
4       0

In [7]:
df.isnull()

        video_id  comment_text  likes  replies
0          False         False  False    False
1          False         False  False    False
2          False         False  False    False
3          False         False  False    False
4          False         False  False    False
...          ...           ...    ...      ...
691395     False         False  False    False
691396     False         False  False    False
691397     False         False  False    False
691398     False         False  False    False
691399     False         False  False    False

[691400 rows x 4 columns]

In [10]:
df.isnull().sum()

video_id         0
comment_text    26
likes            0
replies          0
dtype: int64

In [11]:
df.dropna()

,video_id,comment_text,likes,replies
0,XpVt6Z1Gjjo,Logan Paul it's yo big day ‼️‼️‼️,4,0
1,XpVt6Z1Gjjo,I've been following you from the start of your...,3,0
2,XpVt6Z1Gjjo,Say hi to Kong and maverick for me,3,0
3,XpVt6Z1Gjjo,MY FAN . attendance,3,0
4,XpVt6Z1Gjjo,trending 😉,3,0
...,...,...,...,...
691395,EoejGgUNmVU,Лучшая,1,0
691396,EoejGgUNmVU,qu'est ce que j'aimerais que tu viennes à Roan...,0,0
691397,EoejGgUNmVU,Ven a mexico! 😍 te amo LP,0,0
691398,EoejGgUNmVU,Islığı yeter...,0,0
691399,EoejGgUNmVU,Kocham tą piosenkę😍❤❤❤byłam zakochana po uszy ...,0,0

In [12]:
df.dropna()

,video_id,comment_text,likes,replies
0,XpVt6Z1Gjjo,Logan Paul it's yo big day ‼️‼️‼️,4,0
1,XpVt6Z1Gjjo,I've been following you from the start of your...,3,0
2,XpVt6Z1Gjjo,Say hi to Kong and maverick for me,3,0
3,XpVt6Z1Gjjo,MY FAN . attendance,3,0
4,XpVt6Z1Gjjo,trending 😉,3,0
...,...,...,...,...
691395,EoejGgUNmVU,Лучшая,1,0
691396,EoejGgUNmVU,qu'est ce que j'aimerais que tu viennes à Roan...,0,0
691397,EoejGgUNmVU,Ven a mexico! 😍 te amo LP,0,0
691398,EoejGgUNmVU,Islığı yeter...,0,0
691399,EoejGgUNmVU,Kocham tą piosenkę😍❤❤❤byłam zakochana po uszy ...,0,0

In [16]:
df=pd.read_csv("UScomments.csv")

ParserError: Error tokenizing data. C error: Expected 4 fields in line 41589, saw 11

In [19]:
rows, columns = df.shape
print(f"Rows: {rows}, Columns: {columns}")

Rows: 691400, Columns: 4